### ISSUE TITLE
Many file paths do not understand where the data preprocessing steps come from, could you improve it?

### ISSUE THREAD

**Issue by ZhichaoOuyang** [acleclair/ICPC2020_GNN#10]
I want to use your method as my baseline, the data set is different from yours, but I don’t understand your preprocessing steps because of many unknown paths and files.
Thank you very much!

**Comment by DRMALEK** [comment]
Any update on the issue? I'm facing the same problem. 
Thanks!

**Comment by ZhichaoOuyang** [comment]
> Any update on the issue? I'm facing the same problem.
> Thanks!

Sorry. I did not get a reply from the author.

**Comment by acleclair** [comment]
The preprocessing code was added to show the steps we took to produce the final dataset that we provide. In the readme there is a section on the preprocessing files

"We have added our processing files to the processing directory. These files will not work without some tweaking due to hard coded paths/file names/databases but show how we processed our code, comments, and AST. To generate the base AST XML we use SrCML which can be downloaded HERE"

If you look at the code in the preprocessing files (mainly 1_comset, 2_datset, 3_smlset) you will see just 1-2 processing steps. If you have your code and comments then all you need to do is split camel case and remove special characters. If you use SrCML to parse the AST then you can follow the code in 3_smlset.py. 

I currently have no plan to generalize the processing pipeline.

**Comment by ztw33** [comment]
> I want to use your method as my baseline, the data set is different from yours, but I don’t understand your preprocessing steps because of many unknown paths and files.
> Thank you very much!

Hello, sorry if I bother you, I have been troubled with the preprocessing steps for a long time and don't know how to adapt my dataset to theirs. I read your paper "BASTS", it seems you have successfully run their model. May I please ask how you generate `dataset.pkl`, `tdats.tok`, `smls.tok` and `coms.tok` for your own dataset?
Thanks very much!
